version: "3.8"

services:
  rahoot:
    image: ralex91/rahoot:latest
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./config:/app/quizz # Path to your quizz files
    environment:
      - WEB_ORIGIN=${WEB_ORIGIN}
      - SOCKET_URL=${SOCKET_URL}
      - MANAGER_PASSWORD=${MANAGER_PASSWORD}
      - MUSIC_ENABLED=${MUSIC_ENABLED}
